CREATE TABLE `payments` (
  `npi` varchar(255) DEFAULT NULL,
  `nppes_provider_last_org_name` varchar(255) DEFAULT NULL,
  `nppes_provider_first_name` varchar(255) DEFAULT NULL,
  `nppes_provider_mi` char(2) DEFAULT NULL,
  `nppes_credentials` varchar(255) DEFAULT NULL,
  `nppes_provider_gender` char(2) DEFAULT NULL,
  `nppes_entity_code` char(3) DEFAULT NULL,
  `nppes_provider_street1` varchar(255) DEFAULT NULL,
  `nppes_provider_street2` varchar(255) DEFAULT NULL,
  `nppes_provider_city` varchar(255) DEFAULT NULL,
  `nppes_provider_zip` varchar(12) DEFAULT NULL,
  `nppes_provider_state` char(6) DEFAULT NULL,
  `nppes_provider_country` char(4) DEFAULT NULL,
  `provider_type` varchar(255) DEFAULT NULL,
  `medicare_participation_indicator` char(2) DEFAULT NULL,
  `place_of_service` char(2) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `hcpcs_code` varchar(255) DEFAULT NULL,
  `hcpcs_description` varchar(255) DEFAULT NULL,
  `line_srvc_cnt` int(11) DEFAULT NULL,
  `bene_unique_cnt` int(11) DEFAULT NULL,
  `bene_day_srvc_cnt` int(11) DEFAULT NULL,
  `average_Medicare_allowed_amt` float(16,3) DEFAULT NULL,
  `stdev_Medicare_allowed_amt` float(16,3) DEFAULT NULL,
  `average_submitted_chrg_amt` float(16,3) DEFAULT NULL,
  `stdev_submitted_chrg_amt` float(16,3) DEFAULT NULL,
  `average_Medicare_payment_amt` float(16,3) DEFAULT NULL,
  `stdev_Medicare_payment_amt` float(16,3) DEFAULT NULL,
  KEY `index_cmsfee_on_state_and_city` (`nppes_provider_state`,`nppes_provider_city`),
  KEY `index_cmsfee_on_provider_type` (`provider_type`),
  KEY `index_cmsfee_on_npi` (`npi`),
  KEY `index_cmsfee_hcpcs_code` (`hcpcs_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
